-- ============================================================
-- Ravenscraft Visuals — Supabase setup script
--
-- HOW TO USE:
-- 1. Go to supabase.com and create a free project.
-- 2. In your project, open "SQL Editor" in the left sidebar.
-- 3. Click "New query", paste this ENTIRE file, and click "Run".
-- 4. Go to "Authentication" > "Users" > "Add user" and create your own
--    admin login (any email + password). Toggle "Auto Confirm User" ON.
-- 5. Go to "Project Settings" > "API Keys" and copy your "Project URL" and
--    "Publishable key" (also called "anon public" key) — paste them into
--    the site's Admin > Setup screen.
-- ============================================================

-- 1) Storage bucket that holds the actual image files
insert into storage.buckets (id, name, public)
values ('ravenscraft-media', 'ravenscraft-media', true)
on conflict (id) do update set public = true;

-- 2) Table for the logo, About-section photo, and portfolio images
create table if not exists public.site_assets (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('logo', 'about', 'portfolio')),
  path text not null unique,
  name text,
  alt text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

-- 3) Table for booking requests submitted from the website
create table if not exists public.bookings (
  id integer generated by default as identity primary key,
  name varchar(120) not null,
  email varchar(200) not null,
  phone varchar(40),
  category varchar(80) not null,
  package_interest varchar(160),
  preferred_date varchar(40),
  location varchar(180),
  message text,
  status varchar(30) not null default 'new',
  created_at timestamptz not null default now()
);

alter table public.site_assets enable row level security;
alter table public.bookings enable row level security;

drop policy if exists "Public can view site assets" on public.site_assets;
create policy "Public can view site assets"
on public.site_assets for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated admins manage site assets" on public.site_assets;
create policy "Authenticated admins manage site assets"
on public.site_assets for all
to authenticated
using (true)
with check (true);

drop policy if exists "Anyone can submit bookings" on public.bookings;
create policy "Anyone can submit bookings"
on public.bookings for insert
to anon, authenticated
with check (true);

drop policy if exists "Authenticated admins view bookings" on public.bookings;
create policy "Authenticated admins view bookings"
on public.bookings for select
to authenticated
using (true);

drop policy if exists "Authenticated admins update bookings" on public.bookings;
create policy "Authenticated admins update bookings"
on public.bookings for update
to authenticated
using (true)
with check (true);

drop policy if exists "Public can read Ravenscraft media" on storage.objects;
create policy "Public can read Ravenscraft media"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'ravenscraft-media');

drop policy if exists "Authenticated admins upload Ravenscraft media" on storage.objects;
create policy "Authenticated admins upload Ravenscraft media"
on storage.objects for insert
to authenticated
with check (bucket_id = 'ravenscraft-media');

drop policy if exists "Authenticated admins update Ravenscraft media" on storage.objects;
create policy "Authenticated admins update Ravenscraft media"
on storage.objects for update
to authenticated
using (bucket_id = 'ravenscraft-media')
with check (bucket_id = 'ravenscraft-media');

drop policy if exists "Authenticated admins delete Ravenscraft media" on storage.objects;
create policy "Authenticated admins delete Ravenscraft media"
on storage.objects for delete
to authenticated
using (bucket_id = 'ravenscraft-media');

-- Done! Everyone (including anonymous visitors) can VIEW media and SUBMIT
-- bookings. Only a signed-in admin (the user you create in step 4) can
-- upload/remove media or view/update bookings.
--
-- No credit card is required for any of this — Supabase's free tier stays
-- free forever within its usage limits (500MB database, 1GB file storage).
-- The only thing to know: a free project auto-pauses after 7 days with no
-- activity. If that happens, just log into supabase.com and click "Resume
-- project" — no data is lost, and it takes about 10 seconds.
