import { FormEvent, useEffect, useRef, useState } from "react";
import {
  clearSupabaseConfig,
  getSupabaseConfig,
  isSupabaseConfigured,
  saveSupabaseConfig,
  testSupabaseConnection,
  type Session,
} from "../lib/supabase";
import { getSession, onAuthChange, signIn, signOut } from "../lib/cloud-auth";
import {
  Booking,
  MediaAsset,
  MediaKind,
  deleteMedia,
  listAllMedia,
  listBookings,
  updateBookingStatus,
  uploadMedia,
} from "../lib/cloud-content";
import { BOOKING_STATUSES } from "../lib/booking-data";
import { formatFileSize, prepareImageForUpload } from "../lib/image-upload";

const STATUS_COLORS: Record<string, string> = {
  new: "bg-blue-500/20 text-blue-300",
  contacted: "bg-amber-500/20 text-amber-300",
  "deposit-pending": "bg-purple-500/20 text-purple-300",
  confirmed: "bg-emerald-500/20 text-emerald-300",
  completed: "bg-slate-500/20 text-slate-300",
  cancelled: "bg-red-500/20 text-red-300",
};

const SETUP_SQL = `-- Paste this whole script into Supabase's SQL Editor and click Run.

insert into storage.buckets (id, name, public)
values ('ravenscraft-media', 'ravenscraft-media', true)
on conflict (id) do update set public = true;

create table if not exists public.site_assets (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('logo', 'about', 'portfolio')),
  path text not null unique,
  name text,
  alt text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.bookings (
  id integer generated by default as identity primary key,
  name varchar(120) not null,
  email varchar(200) not null,
  phone varchar(40),
  category varchar(80) not null,
  package_interest varchar(160),
  preferred_date varchar(40),
  location varchar(180),
  message text,
  status varchar(30) not null default 'new',
  created_at timestamptz not null default now()
);

alter table public.site_assets enable row level security;
alter table public.bookings enable row level security;

drop policy if exists "Public can view site assets" on public.site_assets;
create policy "Public can view site assets"
on public.site_assets for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated admins manage site assets" on public.site_assets;
create policy "Authenticated admins manage site assets"
on public.site_assets for all
to authenticated
using (true)
with check (true);

drop policy if exists "Anyone can submit bookings" on public.bookings;
create policy "Anyone can submit bookings"
on public.bookings for insert
to anon, authenticated
with check (true);

drop policy if exists "Authenticated admins view bookings" on public.bookings;
create policy "Authenticated admins view bookings"
on public.bookings for select
to authenticated
using (true);

drop policy if exists "Authenticated admins update bookings" on public.bookings;
create policy "Authenticated admins update bookings"
on public.bookings for update
to authenticated
using (true)
with check (true);

drop policy if exists "Public can read Ravenscraft media" on storage.objects;
create policy "Public can read Ravenscraft media"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'ravenscraft-media');

drop policy if exists "Authenticated admins upload Ravenscraft media" on storage.objects;
create policy "Authenticated admins upload Ravenscraft media"
on storage.objects for insert
to authenticated
with check (bucket_id = 'ravenscraft-media');

drop policy if exists "Authenticated admins update Ravenscraft media" on storage.objects;
create policy "Authenticated admins update Ravenscraft media"
on storage.objects for update
to authenticated
using (bucket_id = 'ravenscraft-media')
with check (bucket_id = 'ravenscraft-media');

drop policy if exists "Authenticated admins delete Ravenscraft media" on storage.objects;
create policy "Authenticated admins delete Ravenscraft media"
on storage.objects for delete
to authenticated
using (bucket_id = 'ravenscraft-media');
`;

function CopyButton({ text, label = "Copy" }: { text: string; label?: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      type="button"
      onClick={async () => {
        await navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      }}
      className="rounded-full border border-white/20 px-3 py-1.5 text-xs font-semibold text-white transition hover:border-[#d4af63] hover:text-[#e7c982]"
    >
      {copied ? "Copied!" : label}
    </button>
  );
}

function SetupScreen({ onConfigured }: { onConfigured: () => void }) {
  const existing = getSupabaseConfig();
  const [url, setUrl] = useState(existing.url);
  const [anonKey, setAnonKey] = useState(existing.key);
  const [error, setError] = useState("");
  const [testResult, setTestResult] = useState<{ ok: boolean; message: string } | null>(null);
  const [testing, setTesting] = useState(false);

  async function handleTest() {
    setTesting(true);
    setTestResult(null);
    setError("");
    const result = await testSupabaseConnection(url, anonKey);
    setTestResult(
      result.ok
        ? { ok: true, message: "✅ Connected! Your database and tables are set up correctly." }
        : { ok: false, message: result.message },
    );
    setTesting(false);
  }

  function handleSave(event: FormEvent) {
    event.preventDefault();
    if (!url.trim() || !anonKey.trim()) {
      setError("Please paste both your Project URL and anon public key.");
      return;
    }
    if (!/^https:\/\/.+\.supabase\.co\/?$/.test(url.trim())) {
      setError('That doesn\'t look like a Supabase Project URL (should look like "https://xxxx.supabase.co").');
      return;
    }
    saveSupabaseConfig(url.trim(), anonKey.trim());
    setError("");
    onConfigured();
  }

  return (
    <div className="mx-auto max-w-3xl px-4 py-6">
      <h1 className="font-display text-3xl font-semibold text-white">Connect Your Database</h1>
      <p className="mt-2 text-slate-400">
        This site saves your logo, About photo, portfolio images, and booking requests to a real
        online database — completely free, no credit card, ever. Visible to every visitor on every
        device. It takes about 10 minutes, one time only. A full easy guide is also saved in this
        project as <span className="font-semibold text-white">LAUNCH_GUIDE.md</span>.
      </p>

      <ol className="mt-8 space-y-6">
        <li className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
          <p className="text-xs font-bold uppercase tracking-[0.25em] text-[#d4af63]">Step 1</p>
          <h2 className="font-display mt-1 text-lg font-semibold text-white">
            Create a free Supabase project
          </h2>
          <p className="mt-2 text-sm text-slate-400">
            Go to{" "}
            <a
              href="https://supabase.com"
              target="_blank"
              rel="noreferrer"
              className="font-semibold text-[#e7c982] underline"
            >
              supabase.com
            </a>{" "}
            and create a free account and a new project (pick any name and password for the
            database — you won't need that password again).
          </p>
        </li>

        <li className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
          <div className="flex items-start justify-between gap-3">
            <div>
              <p className="text-xs font-bold uppercase tracking-[0.25em] text-[#d4af63]">Step 2</p>
              <h2 className="font-display mt-1 text-lg font-semibold text-white">
                Run this setup script
              </h2>
              <p className="mt-2 text-sm text-slate-400">
                In your Supabase project, open <span className="text-white">SQL Editor</span> →{" "}
                <span className="text-white">New query</span>, paste the script below, and click{" "}
                <span className="text-white">Run</span>. This creates everything needed: the
                photo/booking tables and the storage bucket.
              </p>
            </div>
            <CopyButton text={SETUP_SQL} label="Copy SQL" />
          </div>
          <pre className="mt-4 max-h-56 overflow-auto rounded-xl bg-black/40 p-4 text-[11px] leading-relaxed text-slate-300">
            {SETUP_SQL}
          </pre>
        </li>

        <li className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
          <p className="text-xs font-bold uppercase tracking-[0.25em] text-[#d4af63]">Step 3</p>
          <h2 className="font-display mt-1 text-lg font-semibold text-white">
            Create your admin login
          </h2>
          <p className="mt-2 text-sm text-slate-400">
            In Supabase, go to <span className="text-white">Authentication</span> →{" "}
            <span className="text-white">Users</span> → <span className="text-white">Add user</span>.
            Enter any email and password you'll remember, and toggle{" "}
            <span className="font-semibold text-white">"Auto Confirm User"</span> ON. This is what
            you'll log in with below.
          </p>
        </li>

        <li className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
          <p className="text-xs font-bold uppercase tracking-[0.25em] text-[#d4af63]">Step 4</p>
          <h2 className="font-display mt-1 text-lg font-semibold text-white">
            Connect this site to your project
          </h2>
          <p className="mt-2 text-sm text-slate-400">
            In Supabase, go to <span className="text-white">Settings</span> →{" "}
            <span className="text-white">General</span> to copy your{" "}
            <span className="text-white">Project URL</span>. Then go to{" "}
            <span className="text-white">Settings</span> → <span className="text-white">API Keys</span>{" "}
            to copy your <span className="text-white">Publishable key</span> (also called the
            "anon public" key). Paste both below.
          </p>

          <form onSubmit={handleSave} className="mt-4 space-y-3">
            <div>
              <label className="mb-1 block text-xs font-semibold uppercase tracking-wide text-slate-400">
                Project URL
              </label>
              <input
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                placeholder="https://xxxxxxxxxxxx.supabase.co"
                className="w-full rounded-xl border border-white/15 bg-white/[0.04] px-4 py-3 text-sm text-white placeholder:text-slate-500 focus:border-[#d4af63] focus:outline-none"
              />
            </div>
            <div>
              <label className="mb-1 block text-xs font-semibold uppercase tracking-wide text-slate-400">
                Publishable key (anon public key)
              </label>
              <input
                value={anonKey}
                onChange={(e) => setAnonKey(e.target.value)}
                placeholder="sb_publishable_..."
                className="w-full rounded-xl border border-white/15 bg-white/[0.04] px-4 py-3 text-sm text-white placeholder:text-slate-500 focus:border-[#d4af63] focus:outline-none"
              />
            </div>
            {testResult && (
              <p
                className={`rounded-xl border px-4 py-3 text-sm ${
                  testResult.ok
                    ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-200"
                    : "border-red-500/30 bg-red-500/10 text-red-200"
                }`}
              >
                {testResult.message}
              </p>
            )}
            {error && (
              <p className="rounded-xl border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-200">
                {error}
              </p>
            )}
            <div className="flex flex-col gap-3 sm:flex-row">
              <button
                type="button"
                onClick={() => void handleTest()}
                disabled={testing}
                className="w-full rounded-full border border-white/20 px-6 py-3 text-sm font-semibold text-white transition hover:border-[#d4af63] hover:text-[#e7c982] disabled:opacity-60 sm:w-auto"
              >
                {testing ? "Testing…" : "🔎 Test Connection"}
              </button>
              <button
                type="submit"
                className="w-full rounded-full bg-gradient-to-r from-[#a7762a] via-[#d4af63] to-[#8a6528] px-6 py-3 text-sm font-bold text-black sm:flex-1"
              >
                Save & Continue
              </button>
            </div>
            <p className="text-xs text-slate-500">
              Tip: press <span className="font-semibold text-slate-300">Test Connection</span>{" "}
              first — it tells you immediately if something's not set up right, before you try to
              log in.
            </p>
          </form>
        </li>
      </ol>

      <div className="mt-8 rounded-2xl border border-[#d4af63]/25 bg-[#d4af63]/5 p-5 text-sm leading-relaxed text-slate-300">
        <p className="font-semibold text-[#e7c982]">Important — making this permanent for every visitor</p>
        <p className="mt-2">
          Saving here connects <span className="font-semibold text-white">this browser</span> to
          your database so you can finish setup and test everything right now. To make your photos
          visible to <span className="font-semibold text-white">every visitor on every device</span>,
          send this same Project URL and anon public key back in the chat — they'll be built
          permanently into the live site, no credit card or extra technical steps needed.
        </p>
      </div>
    </div>
  );
}

function AdminLoginForm({ onAuthenticated }: { onAuthenticated: (session: Session) => void }) {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setLoading(true);
    setError("");

    try {
      const session = await signIn(email, password);
      onAuthenticated(session);
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Login could not be completed. Please check your email and password.",
      );
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="mx-auto flex min-h-[70svh] max-w-md flex-col justify-center px-6">
      <h1 className="font-display text-3xl font-semibold text-white">Studio Admin</h1>
      <p className="mt-2 text-base text-slate-400">
        Log in with the admin email and password you created in Supabase.
      </p>
      <form onSubmit={handleSubmit} className="mt-6 space-y-4">
        <div>
          <label htmlFor="admin-email" className="mb-1.5 block text-sm font-semibold text-white">
            Email
          </label>
          <input
            id="admin-email"
            type="email"
            value={email}
            onChange={(event) => setEmail(event.target.value)}
            required
            autoComplete="username"
            className="w-full rounded-xl border border-white/15 bg-white/[0.04] px-4 py-3 text-white placeholder:text-slate-500 focus:border-[#d4af63] focus:outline-none"
          />
        </div>
        <div>
          <label htmlFor="admin-password" className="mb-1.5 block text-sm font-semibold text-white">
            Password
          </label>
          <input
            id="admin-password"
            type="password"
            value={password}
            onChange={(event) => setPassword(event.target.value)}
            required
            autoComplete="current-password"
            className="w-full rounded-xl border border-white/15 bg-white/[0.04] px-4 py-3 text-white placeholder:text-slate-500 focus:border-[#d4af63] focus:outline-none"
          />
        </div>
        {error && (
          <p className="rounded-xl border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-200">
            {error}
          </p>
        )}
        <button
          type="submit"
          disabled={loading}
          className="w-full rounded-full bg-gradient-to-r from-[#a7762a] via-[#d4af63] to-[#8a6528] px-6 py-3 text-sm font-bold text-black disabled:opacity-60"
        >
          {loading ? "Logging In…" : "Log In"}
        </button>
        <button
          type="button"
          onClick={() => {
            clearSupabaseConfig();
            window.location.reload();
          }}
          className="w-full text-center text-xs text-slate-500 underline hover:text-slate-300"
        >
          Connected to the wrong project? Reset database connection
        </button>
      </form>
    </div>
  );
}

function MediaManager() {
  const [media, setMedia] = useState<MediaAsset[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedLogo, setSelectedLogo] = useState<File | null>(null);
  const [selectedAboutPhoto, setSelectedAboutPhoto] = useState<File | null>(null);
  const [selectedPortfolio, setSelectedPortfolio] = useState<File[]>([]);
  const [saving, setSaving] = useState(false);
  const [progress, setProgress] = useState("");
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const logoInputRef = useRef<HTMLInputElement>(null);
  const aboutPhotoInputRef = useRef<HTMLInputElement>(null);
  const portfolioInputRef = useRef<HTMLInputElement>(null);

  async function refresh() {
    setLoading(true);
    try {
      setMedia(await listAllMedia());
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not load your media library.");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    void refresh();
  }, []);

  const logo = [...media].reverse().find((m) => m.kind === "logo") ?? null;
  const aboutPhoto = [...media].reverse().find((m) => m.kind === "about") ?? null;
  const portfolio = media.filter((m) => m.kind === "portfolio");

  async function uploadOne(kind: MediaKind, file: File) {
    const prepared = await prepareImageForUpload(file, kind);
    await uploadMedia(kind, prepared);
  }

  async function saveChanges() {
    if (!selectedLogo && !selectedAboutPhoto && selectedPortfolio.length === 0) {
      setError("Choose an image before pressing Save Changes.");
      return;
    }

    setSaving(true);
    setError("");
    setMessage("");

    try {
      let savedCount = 0;

      if (selectedLogo) {
        setProgress(`Uploading ${selectedLogo.name}…`);
        await uploadOne("logo", selectedLogo);
        savedCount += 1;
      }

      if (selectedAboutPhoto) {
        setProgress(`Uploading ${selectedAboutPhoto.name}…`);
        await uploadOne("about", selectedAboutPhoto);
        savedCount += 1;
      }

      for (const [index, file] of selectedPortfolio.entries()) {
        setProgress(`Photo ${index + 1} of ${selectedPortfolio.length}: ${file.name}`);
        await uploadOne("portfolio", file);
        savedCount += 1;
      }

      setSelectedLogo(null);
      setSelectedAboutPhoto(null);
      setSelectedPortfolio([]);
      if (logoInputRef.current) logoInputRef.current.value = "";
      if (aboutPhotoInputRef.current) aboutPhotoInputRef.current.value = "";
      if (portfolioInputRef.current) portfolioInputRef.current.value = "";

      await refresh();

      setMessage(
        `${savedCount} image${savedCount === 1 ? " was" : "s were"} saved to your live website — visible to everyone now.`,
      );
    } catch (saveError) {
      setError(
        saveError instanceof Error
          ? saveError.message
          : "The images could not be saved. Please try again.",
      );
    } finally {
      setProgress("");
      setSaving(false);
    }
  }

  async function handleRemove(asset: MediaAsset) {
    if (!window.confirm("Remove this image from the live website?")) return;
    try {
      await deleteMedia(asset);
      await refresh();
      setMessage("Removed and updated on the live website.");
      setError("");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not remove this image.");
    }
  }

  const pendingCount =
    (selectedLogo ? 1 : 0) + (selectedAboutPhoto ? 1 : 0) + selectedPortfolio.length;

  return (
    <section className="rounded-[2rem] border border-white/10 bg-white/[0.03] p-6 sm:p-8">
      <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <p className="font-script text-3xl text-[#e7c982] sm:text-4xl">Brand & Portfolio Uploads</p>
          <h2 className="font-display mt-1 text-2xl font-semibold text-white">
            Add your logo, About photo, and portfolio
          </h2>
          <p className="mt-2 max-w-3xl text-sm leading-relaxed text-slate-400">
            Saved here permanently to your live database — every visitor on every device sees the
            same photos, right away. First choose your files, then press Save Changes.
          </p>
        </div>
        <div className="flex flex-wrap gap-3">
          <button
            type="button"
            onClick={() => void saveChanges()}
            disabled={saving || pendingCount === 0}
            className="rounded-full bg-gradient-to-r from-[#a7762a] via-[#d4af63] to-[#8a6528] px-6 py-3 text-sm font-bold text-black shadow-lg shadow-black/30 transition hover:scale-[1.02] disabled:cursor-not-allowed disabled:opacity-45"
          >
            {saving ? "Saving Changes…" : `Save Changes${pendingCount ? ` (${pendingCount})` : ""}`}
          </button>
          <a
            href="#/"
            className="rounded-full border border-white/20 px-5 py-3 text-sm font-semibold text-white transition hover:border-[#d4af63] hover:text-[#e7c982]"
          >
            View Live Site
          </a>
        </div>
      </div>

      {(error || message || progress) && (
        <div
          className={`mt-6 rounded-2xl border px-4 py-3 text-sm ${
            error
              ? "border-red-500/30 bg-red-500/10 text-red-200"
              : message
                ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-200"
                : "border-[#d4af63]/30 bg-[#d4af63]/10 text-[#f0d48d]"
          }`}
        >
          {error || message || progress}
        </div>
      )}

      {loading ? (
        <p className="mt-8 text-sm text-slate-400">Loading your media library…</p>
      ) : (
        <div className="mt-8 grid gap-8 xl:grid-cols-2">
          <div className="rounded-[1.75rem] border border-white/10 bg-black/20 p-5">
            <div className="flex items-start justify-between gap-4">
              <div>
                <p className="text-xs font-bold uppercase tracking-[0.25em] text-[#d4af63]">Step 1</p>
                <h3 className="font-display mt-1 text-xl font-semibold text-white">Choose Your Logo</h3>
                <p className="mt-1 text-sm text-slate-400">
                  This must be your original Ravenscraft Visuals logo image.
                </p>
              </div>
              {logo && (
                <button
                  type="button"
                  onClick={() => void handleRemove(logo)}
                  className="rounded-full border border-white/15 px-3 py-1.5 text-xs font-semibold text-slate-200 hover:border-red-400 hover:text-red-300"
                >
                  Remove
                </button>
              )}
            </div>

            <div className="mt-5 rounded-[1.5rem] border border-[#d4af63]/30 bg-black/30 p-4">
              {logo ? (
                <div className="relative mx-auto aspect-square w-full max-w-[16rem] overflow-hidden rounded-full border-4 border-[#d4af63] bg-white shadow-[0_0_0_4px_rgba(212,175,99,0.18)]">
                  <img
                    src={logo.url}
                    alt="Ravenscraft Visuals logo"
                    className="absolute inset-0 h-full w-full object-contain p-2"
                  />
                </div>
              ) : (
                <div className="rounded-2xl border border-dashed border-white/15 px-5 py-12 text-center text-sm text-slate-400">
                  No original logo is saved yet.
                </div>
              )}
            </div>

            <label className="mt-5 block text-sm font-semibold text-white" htmlFor="admin-logo-upload">
              Select logo file
            </label>
            <input
              id="admin-logo-upload"
              ref={logoInputRef}
              type="file"
              accept="image/*,.jpg,.jpeg,.png,.webp,.avif,.heic,.heif"
              onChange={(event) => {
                setSelectedLogo(event.target.files?.[0] ?? null);
                setError("");
                setMessage("");
              }}
              className="mt-2 block w-full text-sm text-slate-300 file:mr-4 file:rounded-full file:border-0 file:bg-white/10 file:px-4 file:py-2 file:text-sm file:font-semibold file:text-white"
            />
            {selectedLogo && (
              <p className="mt-3 rounded-xl bg-white/[0.04] px-3 py-2 text-sm text-[#f0d48d]">
                Ready to save: {selectedLogo.name} ({formatFileSize(selectedLogo.size)})
              </p>
            )}
          </div>

          <div className="rounded-[1.75rem] border border-white/10 bg-black/20 p-5">
            <div className="flex items-start justify-between gap-4">
              <div>
                <p className="text-xs font-bold uppercase tracking-[0.25em] text-[#d4af63]">Step 2</p>
                <h3 className="font-display mt-1 text-xl font-semibold text-white">
                  About Section Photo
                </h3>
                <p className="mt-1 text-sm text-slate-400">
                  A photo of you at work — shown on the website's About section.
                </p>
              </div>
              {aboutPhoto && (
                <button
                  type="button"
                  onClick={() => void handleRemove(aboutPhoto)}
                  className="rounded-full border border-white/15 px-3 py-1.5 text-xs font-semibold text-slate-200 hover:border-red-400 hover:text-red-300"
                >
                  Remove
                </button>
              )}
            </div>

            <div className="mt-5 overflow-hidden rounded-[1.5rem] border border-[#d4af63]/30 bg-black/30">
              {aboutPhoto ? (
                <img src={aboutPhoto.url} alt="About section preview" className="h-56 w-full object-cover" />
              ) : (
                <div className="rounded-2xl border border-dashed border-white/15 px-5 py-12 text-center text-sm text-slate-400">
                  No About photo is saved yet. The gold brand seal is shown until you add one.
                </div>
              )}
            </div>

            <label
              className="mt-5 block text-sm font-semibold text-white"
              htmlFor="admin-about-photo-upload"
            >
              Select About section photo
            </label>
            <input
              id="admin-about-photo-upload"
              ref={aboutPhotoInputRef}
              type="file"
              accept="image/*,.jpg,.jpeg,.png,.webp,.avif,.heic,.heif"
              onChange={(event) => {
                setSelectedAboutPhoto(event.target.files?.[0] ?? null);
                setError("");
                setMessage("");
              }}
              className="mt-2 block w-full text-sm text-slate-300 file:mr-4 file:rounded-full file:border-0 file:bg-white/10 file:px-4 file:py-2 file:text-sm file:font-semibold file:text-white"
            />
            {selectedAboutPhoto && (
              <p className="mt-3 rounded-xl bg-white/[0.04] px-3 py-2 text-sm text-[#f0d48d]">
                Ready to save: {selectedAboutPhoto.name} ({formatFileSize(selectedAboutPhoto.size)})
              </p>
            )}
          </div>

          <div className="rounded-[1.75rem] border border-white/10 bg-black/20 p-5 xl:col-span-2">
            <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
              <div>
                <p className="text-xs font-bold uppercase tracking-[0.25em] text-[#d4af63]">Step 3</p>
                <h3 className="font-display mt-1 text-xl font-semibold text-white">
                  Choose Portfolio Photos
                </h3>
                <p className="mt-1 text-sm text-slate-400">
                  You can select many images at once. Each one is saved separately.
                </p>
              </div>
              <p className="text-xs uppercase tracking-[0.22em] text-[#d4af63]">
                {portfolio.length} saved
              </p>
            </div>

            <label
              className="mt-5 block text-sm font-semibold text-white"
              htmlFor="admin-portfolio-upload"
            >
              Select portfolio images
            </label>
            <input
              id="admin-portfolio-upload"
              ref={portfolioInputRef}
              type="file"
              accept="image/*,.jpg,.jpeg,.png,.webp,.avif,.heic,.heif"
              multiple
              onChange={(event) => {
                setSelectedPortfolio(Array.from(event.target.files ?? []));
                setError("");
                setMessage("");
              }}
              className="mt-2 block w-full text-sm text-slate-300 file:mr-4 file:rounded-full file:border-0 file:bg-white/10 file:px-4 file:py-2 file:text-sm file:font-semibold file:text-white"
            />

            {selectedPortfolio.length > 0 && (
              <div className="mt-4 rounded-xl border border-[#d4af63]/20 bg-[#d4af63]/5 p-3">
                <p className="text-sm font-semibold text-[#f0d48d]">
                  {selectedPortfolio.length} photo{selectedPortfolio.length === 1 ? "" : "s"} ready to save
                </p>
                <ul className="mt-2 max-h-28 space-y-1 overflow-auto text-xs text-slate-300">
                  {selectedPortfolio.map((file) => (
                    <li key={`${file.name}-${file.lastModified}`}>
                      {file.name} — {formatFileSize(file.size)}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {portfolio.length === 0 ? (
              <div className="mt-6 rounded-2xl border border-dashed border-white/15 px-5 py-12 text-center text-sm text-slate-400">
                No portfolio photos are saved yet.
              </div>
            ) : (
              <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">
                {portfolio.map((image) => (
                  <div
                    key={image.id}
                    className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]"
                  >
                    <div className="relative aspect-square w-full overflow-hidden">
                      <img
                        src={image.url}
                        alt={image.fileName}
                        className="absolute inset-0 h-full w-full object-cover"
                      />
                    </div>
                    <div className="space-y-2 p-3">
                      <p className="line-clamp-2 text-xs text-slate-300">{image.fileName}</p>
                      <button
                        type="button"
                        onClick={() => void handleRemove(image)}
                        className="rounded-full border border-white/15 px-3 py-1 text-[11px] font-semibold text-slate-200 hover:border-red-400 hover:text-red-300"
                      >
                        Remove
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      )}

      <div className="sticky bottom-4 z-20 mt-8 flex flex-col items-center justify-between gap-3 rounded-2xl border border-[#d4af63]/35 bg-[#090909]/95 p-4 shadow-2xl shadow-black/50 backdrop-blur sm:flex-row">
        <p className="text-sm text-slate-300">
          {pendingCount > 0
            ? `${pendingCount} new image${pendingCount === 1 ? " is" : "s are"} waiting to be saved.`
            : "Choose a logo, About photo, or portfolio photos above."}
        </p>
        <button
          type="button"
          onClick={() => void saveChanges()}
          disabled={saving || pendingCount === 0}
          className="w-full rounded-full bg-gradient-to-r from-[#a7762a] via-[#d4af63] to-[#8a6528] px-7 py-3 text-sm font-bold text-black transition hover:scale-[1.02] disabled:cursor-not-allowed disabled:opacity-45 sm:w-auto"
        >
          {saving ? "Saving Changes…" : `Save Changes${pendingCount ? ` (${pendingCount})` : ""}`}
        </button>
      </div>
    </section>
  );
}

function BookingsDashboard({ onLogout }: { onLogout: () => void }) {
  const [bookings, setBookings] = useState<Booking[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  async function refresh() {
    setLoading(true);
    setError("");
    try {
      setBookings(await listBookings());
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not load bookings.");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    void refresh();
  }, []);

  async function handleStatusChange(id: number, status: string) {
    setBookings((prev) => prev.map((b) => (b.id === id ? { ...b, status } : b)));
    try {
      await updateBookingStatus(id, status);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not update that booking.");
      await refresh();
    }
  }

  return (
    <section className="rounded-[2rem] border border-white/10 bg-white/[0.03] p-6 sm:p-8">
      <div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center">
        <div>
          <p className="font-script text-3xl text-[#e7c982] sm:text-4xl">Bookings</p>
          <h2 className="font-display mt-1 text-2xl font-semibold text-white">Booking Requests</h2>
          <p className="mt-1 text-sm text-slate-400">
            {bookings.length} total request{bookings.length === 1 ? "" : "s"}
          </p>
        </div>
        <div className="flex gap-3">
          <button
            onClick={() => void refresh()}
            className="rounded-full border border-white/20 px-4 py-2 text-sm font-semibold text-white transition hover:border-[#d4af63]"
          >
            Refresh
          </button>
          <button
            onClick={onLogout}
            className="rounded-full border border-white/20 px-4 py-2 text-sm font-semibold text-white transition hover:border-red-400"
          >
            Log Out
          </button>
        </div>
      </div>

      {error && <p className="mt-6 text-red-400">{error}</p>}

      {loading ? (
        <p className="mt-10 text-slate-400">Loading bookings…</p>
      ) : bookings.length === 0 ? (
        <p className="mt-10 text-slate-400">No booking requests yet.</p>
      ) : (
        <div className="mt-8 overflow-x-auto rounded-2xl border border-white/10">
          <table className="min-w-full divide-y divide-white/10 text-sm">
            <thead className="bg-white/[0.03] text-left text-xs uppercase tracking-wide text-slate-400">
              <tr>
                <th className="px-4 py-3">Received</th>
                <th className="px-4 py-3">Name</th>
                <th className="px-4 py-3">Contact</th>
                <th className="px-4 py-3">Category</th>
                <th className="px-4 py-3">Preferred Date</th>
                <th className="px-4 py-3">Location</th>
                <th className="px-4 py-3">Message</th>
                <th className="px-4 py-3">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/10">
              {bookings.map((b) => (
                <tr key={b.id} className="align-top">
                  <td className="whitespace-nowrap px-4 py-3 text-slate-400">
                    {new Date(b.createdAt).toLocaleDateString()}
                  </td>
                  <td className="px-4 py-3 font-medium text-white">{b.name}</td>
                  <td className="px-4 py-3 text-slate-300">
                    <div>{b.email}</div>
                    {b.phone && <div className="text-slate-500">{b.phone}</div>}
                  </td>
                  <td className="px-4 py-3 text-slate-300">{b.category}</td>
                  <td className="px-4 py-3 text-slate-300">{b.preferredDate || "—"}</td>
                  <td className="px-4 py-3 text-slate-300">{b.location || "—"}</td>
                  <td className="max-w-xs px-4 py-3 text-slate-400">{b.message || "—"}</td>
                  <td className="px-4 py-3">
                    <select
                      value={b.status}
                      onChange={(e) => void handleStatusChange(b.id, e.target.value)}
                      className={`rounded-full border-0 px-3 py-1.5 text-xs font-semibold ${
                        STATUS_COLORS[b.status] ?? "bg-slate-500/20 text-slate-300"
                      }`}
                    >
                      {BOOKING_STATUSES.map((s) => (
                        <option key={s} value={s} className="bg-[#0b0c0f] text-white">
                          {s}
                        </option>
                      ))}
                    </select>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </section>
  );
}

export function AdminPage() {
  const [configured, setConfigured] = useState(() => isSupabaseConfigured());
  const [session, setSession] = useState<Session | null>(null);
  const [loadingSession, setLoadingSession] = useState(true);

  useEffect(() => {
    if (!configured) {
      setLoadingSession(false);
      return;
    }

    let unsubscribe = () => {};
    setLoadingSession(true);

    getSession()
      .then(setSession)
      .catch(() => setSession(null))
      .finally(() => setLoadingSession(false));

    try {
      unsubscribe = onAuthChange(setSession);
    } catch {
      // Supabase not reachable yet — handled by the setup/login screens.
    }

    return () => unsubscribe();
  }, [configured]);

  async function handleLogout() {
    await signOut();
    setSession(null);
  }

  return (
    <div className="min-h-screen bg-[#08090b] text-slate-100">
      <div className="mx-auto flex max-w-7xl flex-col px-6 py-6 sm:px-8">
        <div className="mb-6">
          <a
            href="#/"
            className="inline-flex items-center gap-2 rounded-full border border-[#d4af63]/35 px-4 py-2 text-sm font-semibold text-[#f0d48d] transition hover:border-[#d4af63] hover:bg-[#d4af63]/10"
          >
            <span aria-hidden>←</span>
            Back to Website
          </a>
        </div>

        {!configured ? (
          <SetupScreen onConfigured={() => setConfigured(true)} />
        ) : loadingSession ? (
          <p className="py-20 text-center text-slate-400">Connecting to your database…</p>
        ) : !session ? (
          <AdminLoginForm onAuthenticated={setSession} />
        ) : (
          <div className="flex flex-col gap-8">
            <MediaManager />
            <BookingsDashboard onLogout={() => void handleLogout()} />
          </div>
        )}
      </div>
    </div>
  );
}
